#:schema "https://jj-vcs.github.io/jj/prerelease/config-schema.json"

[user]
name = "Vincent Ging Ho Yim"
email = "cenviity@gmail.com"

[ui]
default-command = "log"
{{- if lookPath "difft" }}
diff-formatter = "difft"
{{- end }}
diff-editor = ":builtin"
merge-editor = "vscode"
pager = ":builtin"
log-word-wrap = true

[merge-tools.difft]
diff-invocation-mode = "file-by-file"

[hints]
resolving-conflicts = false

[colors]
# Highlight hunks with background
"diff removed token" = { bg = "#221111", underline = false }
"diff added token" = { bg = "#002200", underline = false }
"description_multiline" = "blue"

[aliases]
a = ["abandon"]
ci = ["commit"]
# `diff staged`
ds = ["diff", "--from=@--"]
gf = ["git", "fetch"]
gp = ["git", "push"]
n = ["next"]
nc = ["next", "--conflict"]
p = ["prev"]
pc = ["prev", "--conflict"]
rb = ["rebase"]
sq = ["squash"]

# Based on https://github.com/jj-vcs/jj/discussions/5568#discussioncomment-12674748
tug = [
    "bookmark",
    "move",
    "--from=closest_bookmarks()",
    "--to=closest_pushable()",
]

w = ["watch"]
watch = ["util", "exec", "--", "sh", "-c", '''
    hwatch --color --no-title --interval 1 -- jj log --color always $@
    ''', ""]

[snapshot]
auto-update-stale = true

[revset-aliases]
# Based on https://github.com/jj-vcs/jj/discussions/5568#discussioncomment-12674748
"closest_bookmarks()" = "closest_bookmarks(@-)"
"closest_bookmarks(to)" = "heads(::to & bookmarks())"
"closest_pushable()" = "closest_pushable(@-)"
"closest_pushable(to)" = "heads(::to ~ description(exact:'')) & (~empty() | merges())"

# See https://github.com/jj-vcs/jj/blob/main/cli/src/config/revsets.toml
default = "present(@) | ancestors(immutable_heads().., 2) | present(trunk())"

private_commits = "mine() & (description(glob-i:'wip:*') | description(glob-i:'private:*'))"

# Revisions including and after the closest described revision
wip_branch = "heads(::@- ~ description(exact:'') ~ private_commits):: & mutable()"
"desc(pattern)" = "description(pattern)"

[templates]
log = "builtin_log_compact__wip"

[template-aliases]
"abbreviate_timestamp_suffix(s, suffix, abbr)" = '''
if(
    s.ends_with(suffix),
    s.remove_suffix(suffix) ++ label("timestamp", abbr)
)
'''
"abbreviate_relative_timestamp(s)" = '''
coalesce(
    abbreviate_timestamp_suffix(s, " millisecond", "ms"),
    abbreviate_timestamp_suffix(s, " second", "s"),
    abbreviate_timestamp_suffix(s, " minute", "m"),
    abbreviate_timestamp_suffix(s, " hour", "h"),
    abbreviate_timestamp_suffix(s, " day", "d"),
    abbreviate_timestamp_suffix(s, " week", "w"),
    abbreviate_timestamp_suffix(s, " month", "mo"),
    abbreviate_timestamp_suffix(s, " year", "y"),
    s
)
'''
# Taken from the default `format_timestamp(timestamp)`
"format_timestamp_long(timestamp)" = "timestamp.local().format('%Y-%m-%d %H:%M:%S')"
"format_timestamp(timestamp)" = '''
separate(
    ", ",
    coalesce(
        if(timestamp.after("1 minute ago"), label("timestamp", "<=1m")),
        abbreviate_relative_timestamp(timestamp.ago().remove_suffix(' ago').remove_suffix('s'))
    ),
    if(timestamp.before("1 week ago"), format_timestamp_long(timestamp))
)
'''
# For op log timestamps
"format_time_range(time_range)" = '''
concat(
    abbreviate_relative_timestamp(time_range.end().ago().remove_suffix(' ago').remove_suffix('s')),
    label("time", ", lasted "),
    abbreviate_relative_timestamp(time_range.duration().remove_suffix('s'))
)
'''
builtin_log_compact__wip = '''
if(
    root,
    format_root_commit(self),
    label(
        separate(
            if(current_working_copy, "working_copy"),
            if(immutable, "immutable", "mutable"),
            if(conflict, "conflicted"),
        ),
        concat(
            format_short_commit_header(self) ++ "\n",
            separate(
                " ",
                if(empty, empty_commit_marker),
                if(
                    description,
                    separate(
                        " ",
                        description.first_line(),
                        if(
                            description.trim_end() != description.first_line(),
                            label("description_multiline", "[â€¦]")
                        )
                    ),
                    label(if(empty, "empty"), description_placeholder),
                ),
            ) ++ "\n",
            if(self.contained_in("wip_branch"), diff.summary()),
        ),
    )
)
'''

[gg.ui]
theme-override = "dark"
recent-workspaces = ["/Users/cenvii/projects/jj"]
